Repository AY2223S1-CS2103T-T08-4/tp, pull requests merged in 2022-10, with the labels that each got.

#52 Add addq and deleteq
  bin/main/view/DarkTheme.css
  bin/main/view/MainWindow.fxml
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddQCommand.java
  src/main/java/seedu/address/logic/commands/DeleteQCommand.java
  src/main/java/seedu/address/logic/parser/AddQCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteQCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/question/Description.java
  src/main/java/seedu/address/model/question/UniqueQuestionList.java
  src/main/java/seedu/address/model/question/exceptions/DuplicateQuestionException.java
  src/main/java/seedu/address/model/question/exceptions/QuestionNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedQuestion.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/QuestionCard.java
  src/main/java/seedu/address/ui/QuestionListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/QuestionListCard.fxml
  src/main/resources/view/QuestionListPanel.fxml
Labels: type.Bug, priority.High, In progress

#56 Add basics to student class
  src/main/java/seedu/address/logic/commands/AddResponseCommand.java
  src/main/java/seedu/address/logic/parser/AddResponseCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/model/student/exceptions/DuplicateStudentException.java
  src/main/java/seedu/address/model/student/exceptions/StudentNotFoundException.java
Labels: In progress

#60 Add editstu command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/parser/AddStuCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditStuCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/StuEmail.java
  src/main/java/seedu/address/model/student/StuName.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/Telegram.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/StudentListPanel.fxml
Labels: In progress

#61 Add attendance
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: priority.High

#62 Update storage and ui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TutorialCard.java
  src/main/java/seedu/address/ui/TutorialListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorialListCard.fxml
  src/main/resources/view/TutorialListPanel.fxml
Labels: In progress

#98 Add addq implementation notes inside DG
  docs/DeveloperGuide.md
  docs/diagrams/AddQActivityDiagram.puml
  docs/diagrams/AddQSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddQActivityDiagram.png
  docs/images/AddQSequenceDiagram.png
  src/main/java/seedu/address/model/AddressBook.java
Labels: priority.High

#86 Add helpstu and unhelpstu command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddResponseCommand.java
  src/main/java/seedu/address/logic/commands/AddStuCommand.java
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/commands/HelpStuCommand.java
  src/main/java/seedu/address/logic/commands/UnhelpStuCommand.java
  src/main/java/seedu/address/logic/parser/AddStuCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpStuCommandParser.java
  src/main/java/seedu/address/logic/parser/UnhelpStuCommandParser.java
  src/main/java/seedu/address/model/student/HelpTag.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: Merge

#110 UniqueTutorialList test
  src/test/java/seedu/address/model/tutorial/UniqueTutorialListTest.java
  src/test/java/seedu/address/testutil/TutorialBuilder.java
  src/test/java/seedu/address/testutil/TypicalTutorials.java
Labels: Merge

#109 Response test and UniqueStudentList test
  src/test/java/seedu/address/model/student/ResponseTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: Merge

#113 Add AddStuCommand and EditStuCommand Parser Tests
  src/main/java/seedu/address/logic/commands/EditStuCommand.java
  src/main/java/seedu/address/logic/parser/AddStuCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStuCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddStuCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditStuCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: In progress

#115 Update DG, UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: In progress

#118 Update Question commands of UG
  docs/UserGuide.md
Labels: In progress

#177 Fix word wrap issue
  src/main/java/seedu/address/ui/QuestionCard.java
  src/main/resources/view/QuestionListCard.fxml
Labels: Merge

#128 Student and Tutorial command and parser tests
  src/main/java/seedu/address/logic/commands/AddResponseCommand.java
  src/test/java/seedu/address/logic/commands/AddResponseCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MarkTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkTutorialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddResponseCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTutorialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkTutorialCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: Merge
